- README.md
- docs/conf.py
> Setup hosted documentation on ReadTheDocs

- requirements.txt
- setup.py
Update dependency vulnerability for [CVE-2017-18342](https://nvd.nist.gov/vuln/detail/CVE-2017-18342)
> Update pyyaml version for CVE-2017-18342

- kubetest/manager.py
- kubetest/plugin.py
Related:
- #88 
- #92
This limits the test case teardown to only run when setup succeeds. If setup fails, the test will terminate, but nothing has been loaded onto the cluster yet, so there will be nothing to clean up off of the cluster for the test case.
> only run teardown if pytest setup succeeds

- docs/usage.rst
- kubetest/plugin.py
> add --kube-context flag

- docs/markers.rst
- kubetest/manager.py
- kubetest/markers.py
- kubetest/plugin.py
> add applymanifest marker

- Makefile
- requirements.txt
updates project dependencies, and updates the makefile target to actually update the deps, not just recreate requirements.txt from the pinned requirements in setup.py
> update project dependencies in preparation for version bump

- kubetest/utils.py
- tests/test_utils.py
> fix bug where long test names exceed maximum kunernetes resource name length

- examples/get-all-pods-via-fixture/README.md
- examples/get-all-pods-via-fixture/conftest.py
- examples/get-all-pods-via-fixture/manifests/deployment-frontend.yaml
- examples/get-all-pods-via-fixture/manifests/deployment-redis.yaml
- examples/get-all-pods-via-fixture/test_examples.py
Adds example tests for getting pods (related: #104)
> add examples for different ways to get pods via kubetest

- kubetest/plugin.py
this is a quick patch for #110 
Its a bit heavy-handed, but is temporary until #111 is resolved.
> prevent test success when kube-disable flag is set

- kubetest/client.py
- kubetest/manager.py
- kubetest/objects/__init__.py
- kubetest/objects/statefulset.py
- tests/conftest.py
- tests/data/simple-statefulset.yaml
- tests/test_manifest.py
Adding StatefulSet support.
Once this will be approved I will also add DaemonSet support
> adding support for statefulsets

- .jenkins
- Makefile
- kubetest/objects/__init__.py
- setup.cfg
- setup.py
- tox.ini
- updates to some dev flow pieces
- adds linting to ci
- autoformatting
> updates to development flow/tooling

- kubetest/plugin.py
this should fix #130 
This premature optimization was added in 0.3.0. Fixture-defined kubeconfig was not being considered during its implementation.
> bugfix: remove premature optimization preventing test loading with fixture-defined kubeconfig

- kubetest/manager.py
> load daemonsets and statefulsets before deployments

- kubetest/client.py
Hello,
This pull request add get_namespaces method.
thx.
> add get_namespaces()

- kubetest/client.py
Hello,
this pull request to add get_secrets method.
thx.
> add get_secrets()

- docs/examples.rst
- docs/fixtures.rst
- docs/index.rst
- docs/markers.rst
- docs/module_ref.rst
- docs/usage.rst
- docs/writing_tests.rst
- kubetest/markers.py
This PR:
- updates some wording of docs 
- updates docs with some missing info
- various minor formatting updates for consistency
> update docs and some doc formatting

- kubetest/client.py
- kubetest/manager.py
- kubetest/objects/__init__.py
- kubetest/objects/persistentvolumeclaim.py
- tests/conftest.py
- tests/data/simple-persistentvolumeclaim.yaml
- tests/test_manifest.py
Add PVC type
(previous PR regarding PVC #141 )
> add PVC type

- examples/get-all-pods-via-fixture/test_examples.py
- examples/test_deployment.py
- kubetest/__init__.py
- kubetest/client.py
- kubetest/manager.py
- kubetest/objects/__init__.py
- kubetest/objects/ingress.py
- tests/conftest.py
- tests/data/simple-ingress.yaml
- tests/test_manifest.py
> Add Ingress Type

- kubetest/client.py
- kubetest/manager.py
- kubetest/objects/__init__.py
- kubetest/objects/replicaset.py
- tests/conftest.py
- tests/data/simple-replicaset.yaml
- tests/test_manifest.py
- tox.ini
This PR:
- adds support for the ReplicaSet object
- adds very basic unit tests
Addresses #177
> feat: add support for ReplicaSets

- kubetest/client.py
- kubetest/manager.py
- kubetest/manifest.py
- kubetest/objects/ingress.py
- kubetest/objects/persistentvolumeclaim.py
- tests/conftest.py
- tests/test_manager.py
This PR:
- cleans up some divergent  formatting, updates some docstrings, adds in some missing type hinting
> cleanup: formatting, docstrings, type hinting

- kubetest/objects/clusterrolebinding.py
- kubetest/objects/configmap.py
- kubetest/objects/container.py
- kubetest/objects/daemonset.py
- kubetest/objects/deployment.py
- kubetest/objects/endpoints.py
- kubetest/objects/event.py
- kubetest/objects/ingress.py
- kubetest/objects/namespace.py
- kubetest/objects/node.py
- kubetest/objects/persistentvolumeclaim.py
- kubetest/objects/pod.py
- kubetest/objects/replicaset.py
- kubetest/objects/rolebinding.py
- kubetest/objects/secret.py
- kubetest/objects/service.py
- kubetest/objects/statefulset.py
This  PR:
- updates reference links for api objects
> docs: update reference links to latest version for api objects

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- tox.ini
This PR:
- sets up lint and test stages in GH actions
> ci: setup basic github actions

- kubetest/manager.py
- kubetest/objects/networkpolicy.py
- tests/conftest.py
- tests/data/simple-networkpolicy.yaml
- tests/test_manifest.py
> Add basic support for network policies

- kubetest/objects/ingress.py
> Add convenience method for waiting till ingress is usable

- .jenkins
- Makefile
- tox.ini
This PR:
- updates the Jenkins CI config to use the shared ci python pipeline
> ci: update jenkins config to use shared pipeline

- kubetest/objects/endpoints.py
> Fix Endpoints.is_ready failing on endpoints that are ready

- .jenkins
> ci: fix pypi release config, update shared lib version
