vapor-ware/kubetest

kubetest/client.py
kubetest/objects/pod.py
kubetest/response.py
kubetest/utils.py

In this PR, we add a Response wrapper around the proxied requests to pods, and it handles the JSONification. This makes it easier for the user to handle things like a response that returns 500 or 404 -- it will now return a response instead of just raising an exception.

add response wrapper around proxy requests

---

kubetest/objects/api_object.py
kubetest/objects/clusterrolebinding.py
kubetest/objects/configmap.py
kubetest/objects/deployment.py
kubetest/objects/namespace.py
kubetest/objects/pod.py
kubetest/objects/rolebinding.py
kubetest/objects/secret.py
kubetest/objects/service.py

fixes #76 
> **Note:** This isn't the prettiest solution. I initially tried to get apiVersion info and preferred version from the kubernetes api directly (see: https://github.com/kubernetes-client/python/blob/master/examples/example3.py), but that was not working with my cluster. Perhaps in the future, this approach could be investigated again, but for now  this solution will work.

better resource version management

---

kubetest/__init__.py
requirements.txt
setup.py

This PR updates the version of `requests` to 2.20.0 to patch the [CVE-2018-18074](https://nvd.nist.gov/vuln/detail/CVE-2018-18074) vulnerability found in `requests<=2.19.1`.
Bumps the version to 0.0.2 for patch release.

patch: update requests dep for CVE-2018-18074

---

docs/writing_tests.rst
kubetest/plugin.py

So we can use kubetest with temporary clusters
Fixes #84

Make kubeconfig a fixture

---

kubetest/manifest.py
kubetest/markers.py

YAML files can contain multiple YAML documents separated by `---` which
is pretty useful in order to have only one file for a service back by a
deployment.
The problem is loading such multi-document YAML file does not work, and
I get this error:
```
self = <yaml.loader.FullLoader object at 0x7f81bc217048>
def get_single_node(self):
self.get_event()
document = None
if not self.check_event(StreamEndEvent):
document = self.compose_document()
if not self.check_event(StreamEndEvent):
event = self.get_event()
raise ComposerError("expected a single document in the
stream",
document.start_mark, "but found another document",
>                   event.start_mark)
E           yaml.composer.ComposerError: expected a single document in
the stream
E             in "my_multidoc.yaml", line 1, column 1
E …
```

Make manifest load support multi-document YAML files

---

kubetest/objects/deployment.py

see: #89 
I'm opening this up for review/discussion but I am really unsure as to whether this should be merged in or not.
This approach generally works for deployments, making it more flexible with different Deployment configurations and still being able to get their pods without making too many assumptions on what the deployment manifest may or may not define.
It may also work for other objects, but it isn't easily generalizable. Additionally, it will not work for some objects at all. A good example of this is for Services and trying to get the endpoints of a service. With services, the issue is that a service uses the selector labels to match pods, but if this auto-generated label is used, it won't exist on the pods, so it will never create the endpoints correctly.
Open for thoughts and …

get a deployments pods via labels

---

kubetest/plugin.py

related:
- #62
In doing a bunch of testing against a local docker-for-desktop kubernetes cluster without HTTPS configured, I was getting a bunch of InsecureRequestsWarnings. This PR adds a command line option to disable those warnings, allowing for cleaner test output when insecure requests are expected.

add option to suppress unsecure request warnings

---

kubetest/manifest.py
kubetest/markers.py
kubetest/objects/api_object.py

This PR fixes a couple bugs I missed in #99, mostly related to the change in return type of `load_file`.
Still need to add formal unit tests, but this gets things working for now. Getting good test coverage will likely be a larger work item, as the code will likely need a bit of refactoring to make it easier to test/maintain.

fix various bugs missed in recent update for multi-doc yamls

---

Makefile
requirements.txt
setup.py

* updates the `requests` lib, which uses `urllib3`, to bump `urllib3` to `>=1.24.2` (see: [CVE-2019-11324](https://nvd.nist.gov/vuln/detail/CVE-2019-11324))

update dependencies for CVE-2019-11324

---

kubetest/objects/statefulset.py
tox.ini

missed this in the PR review.. minor bug in kubernetes lib api usage

fix typos in client api usage

---

README.md
docs/conf.py
docs/source/kubetest.rst
docs/usage.rst
docs/writing_tests.rst
kubetest/__init__.py
kubetest/plugin.py
tox.ini

This PR deprecates the `--kube-disable` flag.
See #110 and #111 for motivation.
This flag was added early on in order to make testing of the plugin easier by preventing it from trying to setup cluster configuration via kubeconfig when a cluster isn't present (e.g. when running unit tests). Since then, it has ceased to even do that, and was being used more as a way to unintuitively gate functionality, which in some cases appeared to behave as originally intended, but ultimately did not.
This divergence from original goals as well as realizing that there is a way to accomplish the original goal via pytest (https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-name) means that the flag is essentially useless at this point.
* bumps to v0.2.0 in preparation for …

deprecate the --kube-disable flag

---

kubetest/objects/daemonset.py

When adding the DaemonSet support, I forgot the DSs have no replicas terminology at all.
This should fix the issue.

Fixing a bug in DaemonSet.is_ready()

---

kubetest/plugin.py

I've ran into an issue where I have the kubetest plugin installed but I'm running tests that don't use it and I don't want to supply a `--kube-config` cli arg in such case.
The tests are running okay but `teardown` calls are failing because it is trying to delete the test namespace (that wasn't even created) from a cluster on `localhost:443`.
I hope you will approve it because without it I'm in quite a jam.
Thanks!

Don't call test teardown if kube-config argument wasn't provided

---

kubetest/manager.py
kubetest/plugin.py

i've encountered another "corner case":
I'm running a test suite built from both tests that use `kubetest` and tests that don't use it, so `--kube-config` argument is supplied in cli.
**But**, for the tests that don't use `kubetest`, the `kube` fixture is not instantiated --> `manager.setup()` is not called and the `_namespace` **variable** remains `None`. When `manager.teardown()` is called (because `--kube-config` arg was supplied) it is trying to delete the test's namespace by using the `namespace` **property** (which creates a value if the variable is `None`).
I hope I explained myself ok and that the proposed solution is acceptable.

On teardown, check that namespace was created before trying to delete it

---

kubetest/client.py
kubetest/objects/__init__.py
kubetest/objects/event.py

Similar to the existing support for Node objects, Event object can only be read from the API server to make Event-based interactions easier.

Adding read-only support for k8s Event object

---

docs/fixtures.rst
kubetest/plugin.py

fixes #118 
@eranreshef -- let me know if this is the information you were thinking of. This currently exposes:
- `cluster`: The name of the cluster set for the current context.
- `user`: The name of the user set for the current context.
- `context`: The name of the current context.
- `host`: API server address.
- `verify_ssl`: SSL certificate verification when calling the API.

add fixture to provide basic cluster information

---

examples/configs/deployment.yaml
examples/configs/service.yaml
examples/test_deployment.py
examples/test_service.py
kubetest/objects/pod.py
kubetest/response.py

fixes #126 
This PR:
- adds a `http_proxy_post` method for POSTing to pods
- updates the test example to use this, updating the backend deployment to an http echo server
- updates example test expectations accordingly
@plyte -- let me know how this looks to you

add support for HTTP POST to a pod

---

kubetest/__init__.py
kubetest/objects/pod.py
kubetest/response.py

This should fix #128 
This PR also includes a patch version bump in anticipation of it being merged.
The major changes here are:
- revert back to enabling `_preload_content` on the kubernetes request
- parse the response with `ast.literal_eval` first, falling back to `json.load`
- added/updated in-line comments regarding these changes

bug: fix opaque type errors generated from failed requests on pod proxy get/post

---

kubetest/plugin.py

Its been a while since my last contribution 😁
I've encountered a case where I skip a test case on runtime (with `pytest.skip('skip reason')`) and then I get some nasty warnings when `pytest_runtest_makereport` is trying to get container logs.

Skip getting container logs if test was skipped

---

kubetest/plugin.py

I've encountered a situation where `pytest_runtest_makereport` is trying to retrieve logs at the end of a test case that didn't include the `kube` fixture at all. This causes the pytest output to contain irrelevant warnings since the plugin is trying to reach pods from a namespace that doesn't exist.
The fix is pretty simple I believe.

Try to retrive container logs only if kube fixture was used

---

kubetest/objects/daemonset.py
kubetest/objects/deployment.py
kubetest/objects/statefulset.py

When I run the first example using the latest version on pip (0.4.2), the Nginx test fails with:
```
>       assert len(pods) == 3, 'nginx should deploy with three replicas'
E       AssertionError: nginx should deploy with three replicas
E       assert 0 == 3
E        +  where 0 = len([])
```
Some debugging showed that `_add_kubetest_labels()` is called twice: once by the `applymanifests` decorator, and once during `deployments.get_deployments()`. This results in the Deployment and Pods having differed UIDs, which causes `get_pods()` to return an empty list.
This patch fixes the problem by first checking to see if the deployment already has a UID label in its metadata. If so it is retrieved from the Deployment's label, instead of overwritten by a new UID.
There are already some PRs …

Avoid overwriting label when re-initialising Deployment object

---

kubetest/plugin.py

Causes:
```
INTERNALERROR>   File "../lib/python3.7/site-packages/kubetest/plugin.py", line 269, in pytest_runtest_makereport
INTERNALERROR>     if 'kube' in item.fixturenames and call.when == 'call':
INTERNALERROR> AttributeError: 'DoctestItem' object has no attribute 'fixturenames'
```
when run on testsuite with doctests.

Fix Pytest INTERNALERROR when running on with doctests.

---

docs/markers.rst
kubetest/manager.py
kubetest/markers.py
kubetest/plugin.py
tests/test_manager.py

This adds a pytest.mark.namespace marker to control the way namespaces are managed for each test case. Current options are:
* `create`: Whether to create or not the namespace automatically (default: True)
* `name`: Name of the namespace, or autogenerated if None (default: None)
Use cases:
* Users may not have permission to create namespaces, which causes the tests to fail even if the namespace is not needed (we commonly deploy a workload and want to run tests against it, this doesn't require creating any resources)
* Some tests can only be run in given existing namespaces (for example a namespace with service mesh enabled, or with an existing configmap/secret...)

Add namespace marker

---

kubetest/utils.py
tests/test_utils.py

This PR:
- fixes a bug where namespace creation fails for parameterized tests because pytest includes `[` and `]` in the name, which are illegal ns characters.
fixes #146

fix bug in namespace generation for parameterized tests

---

examples/get-all-pods-via-fixture/test_examples.py

This PR:
- updates some example tests so that they can be run from a higher-level directory without failing.

update example so test can run at any directory level

---

kubetest/__init__.py
kubetest/plugin.py
regression/154/README.md
regression/154/test_154.py

This PR:
- adds a check during test teardown to see whether the kubeconfig fixture has been specified
- preemptively bumps version to 0.5.1
fixes #154 (@lfn3)

run test teardown when kubeconfig is specified via fixture

---

kubetest/plugin.py
regression/156-bl/README.md
regression/156-bl/test_156.py
regression/156/README.md
regression/156/test_156.py

This PR:
- gets the kubeconfig from the `kubeconfig` fixture rather than command line args when collecting info for the cluster. this allows a custom kubconfig to be defined and be picked up automatically.
- adds regression tests for the case.
fixes #156

bugfix: use kubeconfig fixture to get config for clusterinfo

---

kubetest/manifest.py

since version 11.x, kubernetes client use openapi_types instead of swagger_types
this commit will auto fit these two situations.
#164 
Signed-off-by: hello-ming <mingyu.wmy@alibaba-inc.com>

support kubernetes client version 11.x

---

docs/examples.rst
docs/usage.rst
kubetest/plugin.py

This PR:
- Adds support for using in-cluster config with kubetest
- Fixes typo in docs
- Adds missing command line flag in docs
fixes #169

feat: add support for using in-cluster config

---

examples/get-all-pods-via-fixture/test_examples.py
examples/test_deployment.py
kubetest/__init__.py
kubetest/objects/service.py

- `connect_post_namespaced_service_proxy_with_path` does not allow for the body of a request, which is weird. So I've bypassed it to utilize `call_api` and thus modified the existing `proxy_http_get` service method for consistency. Let me know if you would rather the original `proxy_http_get`, it is more direct however I do prefer consistency.
- version is updated to `0.6.4` as I'm hoping `Add Ingress Type` i.e. version `0.6.3` can be reviewed and merged it as well.

Add Requests to Services

---

examples/get-all-pods-via-fixture/test_examples.py
kubetest/client.py
kubetest/objects/api_object.py
tests/data/multi-obj-manifest.yaml
tests/objects/test_api_object.py
tests/test_manifest.py

This PR:
-  updates the behavior  of  loading manifest files so that it is able to  load files with multiple object definitions contained within them.

feat: allow multiple objects to be defined in loaded manifests

---

examples/configs/ingress.yaml
examples/test_ingress.py
kubetest/client.py

This PR:
- fixes a bug where the incorrect client was being used for getting ingresses.
fixes #179

bugfix: use the correct api client for getting Ingresses

---

kubetest/client.py
kubetest/objects/api_object.py

This PR:
-  adds a `preferred_client` class method to the base ApiObject class  to get an instance  of the preferred api client for the object
- uses the  preferred client when performing gets via the kubetest client
fixes #181

feat: look up preferred client for objects on kubetest client get/list

---

docs/usage.rst
kubetest/plugin.py

in my pytest configuration I am generating the kubeconfig with boto, and so instead of creating it prior, i am generating it on setup_function, and then setting the kubeconfig env appropriately.

Allow for environment variable "KUBECONFIG"

---

docs/writing_tests.rst
kubetest/plugin.py

Hi there -
I have added support for a `kubecontext` fixture that allows the context to be specified via a fixture to align with the support for the `kubeconfig` fixture.
The default implementation returns the value from the session config.
I need this because I am in a weird world where I am using `kubetest` against an application that is fully async and I need to align the configuration between the sync kubernetes library utilized by kubetest with what is used by the kubernetes_asyncio fork utilized by the main application code.
Docs are updated and tests are clean.

Add support for `kubecontext` fixture.

---

kubetest/manifest.py
kubetest/markers.py

This is still a work in progress but figured I would go ahead and start the dialogue.
This PR introduces the ability to preprocess manifests and render them as templates before they are applied to the cluster. It allows an easy path for getting runtime values into the YAML.
My specific use-case is that I am doing some testing for components that are heavily dependent on Prometheus and Envoy and there are values that I need to get into the configuration. Prometheus is configured off a config map and I need to get the testing namespace and some other odds and ends in there. Editing the resources after creation is cumbersome and slow with the intermediate representations and then services have to be restarted and awaited. I also looked at intercepting the object representations before they …

Introduce Manifest Templates

---

kubetest/plugin.py

This change should resolve https://github.com/vapor-ware/kubetest/issues/205 by referencing the KUBECONFIG environment variable whenever `kubeconfig` is injected from the fixture, rather than only reading it when `kubeconfig` is None in the `kube` fixture.
I tested that this resolves my local issue, and the unit tests all pass after making the change.

Read KUBECONFIG environment variable globally instead of only in kube fixture
